/**
 * Tests for Instruction Manager
 * Tests caching, fetching, and integration with service proxy
 */

const InstructionManager = require('../lib/instructionManager');

describe('Instruction Manager', () => {
  let manager;
  let mockDb;

  beforeAll(() => {
    // Create a mock database
    mockDb = {
      prepare: jest.fn(() => ({
        get: jest.fn(() => null),
        all: jest.fn(() => [])
      }))
    };

    manager = new InstructionManager(mockDb);
  });

  describe('Token Instructions', () => {
    test('should fetch token instructions from database', () => {
      const mockInstructions = {
        id: 'instr_1',
        token_id: 'token_1',
        instructions: 'How to use this API',
        examples: '[]',
        auto_generated: 0,
        learned_from_skill_id: null,
        learned_from_agent_id: null,
        learned_at: null,
        created_at: '2026-03-20T00:00:00Z',
        updated_at: '2026-03-20T00:00:00Z'
      };

      mockDb.prepare = jest.fn(() => ({
        get: jest.fn(() => mockInstructions)
      }));

      const result = manager.getTokenInstructions('token_1');

      expect(result).not.toBeNull();
      expect(result.id).toBe('instr_1');
      expect(result.instructions).toBe('How to use this API');
    });

    test('should return null if no instructions exist', () => {
      mockDb.prepare = jest.fn(() => ({
        get: jest.fn(() => null)
      }));

      const result = manager.getTokenInstructions('unknown_token');

      expect(result).toBeNull();
    });

    test('should parse examples as JSON', () => {
      const mockInstructions = {
        id: 'instr_1',
        token_id: 'token_1',
        instructions: 'Test',
        examples: JSON.stringify([{ endpoint: '/users', method: 'GET' }]),
        auto_generated: 0,
        learned_from_skill_id: null,
        learned_from_agent_id: null,
        learned_at: null,
        created_at: '2026-03-20T00:00:00Z',
        updated_at: '2026-03-20T00:00:00Z'
      };

      const testMockDb = {
        prepare: jest.fn(() => ({
          get: jest.fn(() => mockInstructions)
        }))
      };

      const testManager = new InstructionManager(testMockDb);
      const result = testManager.getTokenInstructions('token_1');

      expect(result).not.toBeNull();
      expect(Array.isArray(result.examples)).toBe(true);
      expect(result.examples.length).toBeGreaterThan(0);
      expect(result.examples[0].endpoint).toBe('/users');
    });
  });

  describe('Service Instructions', () => {
    test('should fetch service-level instructions', () => {
      const mockServiceInstructions = {
        id: 'svc_instr_1',
        service_name: 'github',
        instructions: 'GitHub API guide',
        examples: '[]',
        auto_generated: 1,
        aggregated_from_token_count: 5,
        updated_at: '2026-03-20T00:00:00Z'
      };

      mockDb.prepare = jest.fn(() => ({
        get: jest.fn(() => mockServiceInstructions)
      }));

      const result = manager.getServiceInstructions('github');

      expect(result).not.toBeNull();
      expect(result.serviceName).toBe('github');
      expect(result.instructions).toBe('GitHub API guide');
      expect(result.autoGenerated).toBe(true);
    });

    test('should normalize service name to lowercase in lookup', () => {
      // Just verify the function accepts both uppercase and lowercase
      const result1 = manager.getServiceInstructions('GitHub');
      const result2 = manager.getServiceInstructions('github');
      
      // Both should work (return null in this case since mock returns null)
      expect(result1).toBeDefined();
      expect(result2).toBeDefined();
    });
  });

  describe('Proxy Response Instructions', () => {
    test('should prefer token-specific instructions over service instructions', () => {
      const tokenInstructions = {
        id: 'instr_1',
        instructions: 'Token-specific guide',
        examples: [],
        autoGenerated: false
      };

      manager.getTokenInstructions = jest.fn(() => tokenInstructions);
      manager.getServiceInstructions = jest.fn(() => ({
        instructions: 'Service template'
      }));

      const result = manager.getProxyResponseInstructions('token_1', 'github');

      expect(result.instructions).toBe('Token-specific guide');
      expect(result.source).toBe('token-specific');
    });

    test('should fall back to service instructions', () => {
      manager.getTokenInstructions = jest.fn(() => null);
      manager.getServiceInstructions = jest.fn(() => ({
        id: 'svc_1',
        instructions: 'Service guide',
        examples: [],
        autoGenerated: true
      }));

      const result = manager.getProxyResponseInstructions('token_1', 'github');

      expect(result.instructions).toBe('Service guide');
      expect(result.source).toBe('service-template');
    });

    test('should return null if no instructions available', () => {
      manager.getTokenInstructions = jest.fn(() => null);
      manager.getServiceInstructions = jest.fn(() => null);
      manager.getNextEndpoints = jest.fn(() => []);

      const result = manager.getProxyResponseInstructions('token_1', 'github');

      expect(result).toBeNull();
    });
  });

  describe('Next Endpoints', () => {
    let realManager;

    beforeEach(() => {
      // Use real implementation for endpoint tests
      realManager = new InstructionManager(mockDb);
    });

    test('should return endpoints for known services', () => {
      const endpoints = realManager.getNextEndpoints('github');

      expect(Array.isArray(endpoints)).toBe(true);
      expect(endpoints.length).toBeGreaterThan(0);
      expect(endpoints).toContain('/user');
      expect(endpoints).toContain('/user/repos');
    });

    test('should handle service name case-insensitively', () => {
      const endpoints1 = realManager.getNextEndpoints('GitHub');
      const endpoints2 = realManager.getNextEndpoints('github');

      expect(endpoints1).toEqual(endpoints2);
    });

    test('should return empty array for unknown services', () => {
      const endpoints = realManager.getNextEndpoints('unknown-service');

      expect(Array.isArray(endpoints)).toBe(true);
      expect(endpoints.length).toBe(0);
    });

    test('should provide slack endpoints', () => {
      const endpoints = realManager.getNextEndpoints('slack');

      expect(endpoints).toContain('/auth.test');
      expect(endpoints).toContain('/conversations.list');
    });

    test('should provide discord endpoints', () => {
      const endpoints = realManager.getNextEndpoints('discord');

      expect(endpoints).toContain('/users/@me');
      expect(endpoints).toContain('/channels/{channel_id}/messages');
    });
  });

  describe('Caching', () => {
    test('should cache token instructions', () => {
      const getMock = jest.fn(() => ({
        id: 'instr_1',
        token_id: 'token_1',
        instructions: 'Test',
        examples: null,
        auto_generated: 0,
        learned_from_skill_id: null,
        learned_from_agent_id: null,
        learned_at: null,
        created_at: '2026-03-20T00:00:00Z',
        updated_at: '2026-03-20T00:00:00Z'
      }));

      const testManager = new InstructionManager(mockDb);
      mockDb.prepare = jest.fn(() => ({
        get: getMock
      }));

      testManager.clearCache();
      testManager.getTokenInstructions('token_1');
      testManager.getTokenInstructions('token_1');

      // Should only be called once due to caching - first call hits DB, second uses cache
      expect(getMock).toHaveBeenCalledTimes(1);
    });

    test('should clear all caches', () => {
      const manager = new InstructionManager(mockDb);
      manager.cache.set('test_key', 'test_value');

      expect(manager.cache.get('test_key')).toBe('test_value');

      manager.clearCache();

      expect(manager.cache.get('test_key')).toBeUndefined();
    });

    test('should return cache statistics', () => {
      const manager = new InstructionManager(mockDb);
      const stats = manager.getCacheStats();

      expect(stats).toHaveProperty('keys');
      expect(stats).toHaveProperty('hits');
      expect(stats).toHaveProperty('misses');
    });
  });

  describe('Save Instructions', () => {
    test('should save new token instructions', () => {
      const insertCalled = jest.fn();
      mockDb.prepare = jest.fn(() => ({
        run: insertCalled
      }));

      const result = manager.saveTokenInstructions(
        'token_1',
        'Sample instructions',
        [{ endpoint: '/test' }],
        { autoGenerated: true, skillId: 'skill_1' }
      );

      expect(result.success).toBe(true);
      expect(insertCalled).toHaveBeenCalled();
    });

    test('should handle save errors gracefully', () => {
      mockDb.prepare = jest.fn(() => ({
        run: jest.fn(() => {
          throw new Error('Database error');
        })
      }));

      const result = manager.saveTokenInstructions('token_1', 'Test');

      expect(result.success).toBe(false);
      expect(result.error).toContain('Database error');
    });
  });
});
