/**
 * Instruction Manager - Helper for Token Instructions
 * Provides utilities to fetch, cache, and manage token instructions
 * for use across the API layer
 */

const NodeCache = require('node-cache');

class InstructionManager {
  constructor(db, cacheTtl = 3600) {
    this.db = db;
    this.cache = new NodeCache({ stdTTL: cacheTtl });
  }

  /**
   * Get instructions for a specific token
   * Returns both token-specific and service-level instructions
   */
  getTokenInstructions(tokenId) {
    const cacheKey = `token_instructions:${tokenId}`;
    
    // Check cache first
    const cached = this.cache.get(cacheKey);
    if (cached !== undefined) {
      return cached;
    }

    try {
      // Get token-specific instructions
      const stmt = this.db.prepare(`
        SELECT * FROM vault_token_instructions WHERE token_id = ?
      `);
      const instructions = stmt.get(tokenId);

      if (!instructions) {
        this.cache.set(cacheKey, null);
        return null;
      }

      const result = {
        id: instructions.id,
        tokenId: instructions.token_id,
        instructions: instructions.instructions,
        examples: instructions.examples ? JSON.parse(instructions.examples) : [],
        autoGenerated: instructions.auto_generated === 1,
        learnedFromSkill: instructions.learned_from_skill_id,
        learnedFromAgent: instructions.learned_from_agent_id,
        learnedAt: instructions.learned_at,
        createdAt: instructions.created_at,
        updatedAt: instructions.updated_at
      };

      this.cache.set(cacheKey, result);
      return result;
    } catch (error) {
      console.error('[InstructionManager] Error fetching token instructions:', error);
      return null;
    }
  }

  /**
   * Get service-level instructions
   * Returns global template instructions for a service type
   */
  getServiceInstructions(serviceName) {
    const cacheKey = `service_instructions:${serviceName.toLowerCase()}`;
    
    // Check cache first
    const cached = this.cache.get(cacheKey);
    if (cached !== undefined) {
      return cached;
    }

    try {
      const stmt = this.db.prepare(`
        SELECT * FROM service_type_instructions WHERE service_name = ?
      `);
      const instructions = stmt.get(serviceName.toLowerCase());

      if (!instructions) {
        this.cache.set(cacheKey, null);
        return null;
      }

      const result = {
        id: instructions.id,
        serviceName: instructions.service_name,
        instructions: instructions.instructions,
        examples: instructions.examples ? JSON.parse(instructions.examples) : [],
        autoGenerated: instructions.auto_generated === 1,
        aggregatedFromTokenCount: instructions.aggregated_from_token_count,
        updatedAt: instructions.updated_at
      };

      this.cache.set(cacheKey, result);
      return result;
    } catch (error) {
      console.error('[InstructionManager] Error fetching service instructions:', error);
      return null;
    }
  }

  /**
   * Save token instructions (called by learn-from-api endpoint)
   */
  saveTokenInstructions(tokenId, instructions, examples = null, metadata = {}) {
    try {
      const { v4: uuidv4 } = require('uuid');
      const instructionId = uuidv4();
      const now = new Date().toISOString();

      const stmt = this.db.prepare(`
        INSERT INTO vault_token_instructions (
          id, token_id, instructions, examples, auto_generated,
          learned_from_skill_id, learned_from_agent_id, learned_at,
          created_at, updated_at
        ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
      `);

      stmt.run(
        instructionId,
        tokenId,
        instructions,
        examples ? JSON.stringify(examples) : null,
        metadata.autoGenerated ? 1 : 0,
        metadata.skillId || null,
        metadata.agentId || null,
        metadata.learnedAt || now,
        now,
        now
      );

      // Clear cache
      this.cache.del(`token_instructions:${tokenId}`);

      return {
        success: true,
        id: instructionId,
        message: 'Instructions saved'
      };
    } catch (error) {
      console.error('[InstructionManager] Error saving instructions:', error);
      return {
        success: false,
        error: error.message
      };
    }
  }

  /**
   * Get instructions to include in service proxy response
   * Falls back to service-level instructions if token-specific ones don't exist
   */
  getProxyResponseInstructions(tokenId, serviceName) {
    // Try to get token-specific instructions first
    const tokenInstructions = this.getTokenInstructions(tokenId);
    if (tokenInstructions) {
      return {
        instructions: tokenInstructions.instructions,
        examples: tokenInstructions.examples,
        source: 'token-specific',
        autoGenerated: tokenInstructions.autoGenerated
      };
    }

    // Fall back to service-level instructions
    const serviceInstructions = this.getServiceInstructions(serviceName);
    if (serviceInstructions) {
      return {
        instructions: serviceInstructions.instructions,
        examples: serviceInstructions.examples,
        source: 'service-template',
        autoGenerated: serviceInstructions.autoGenerated
      };
    }

    // No instructions available
    return null;
  }

  /**
   * Get suggested next endpoints based on service type
   * Helps AI agents discover related endpoints to try
   */
  getNextEndpoints(serviceName) {
    const endpoints = {
      'github': [
        '/user',
        '/user/repos',
        '/user/issues',
        '/user/pulls',
        '/orgs/{org}',
        '/repos/{owner}/{repo}'
      ],
      'slack': [
        '/auth.test',
        '/users.list',
        '/conversations.list',
        '/chat.postMessage',
        '/files.list'
      ],
      'discord': [
        '/users/@me',
        '/users/@me/guilds',
        '/channels/{channel_id}/messages',
        '/guilds/{guild_id}/members'
      ],
      'google': [
        '/gmail/v1/users/me/messages',
        '/calendar/v3/calendars/primary/events',
        '/drive/v3/files'
      ],
      'notion': [
        '/databases',
        '/pages',
        '/blocks'
      ],
      'linkedin': [
        '/me',
        '/me/posts',
        '/feed'
      ],
      'twitter': [
        '/tweets/search/recent',
        '/users/me',
        '/tweets/search/stream'
      ]
    };

    return endpoints[serviceName.toLowerCase()] || [];
  }

  /**
   * Clear all caches (useful for testing and cache invalidation)
   */
  clearCache() {
    this.cache.flushAll();
  }

  /**
   * Get cache statistics
   */
  getCacheStats() {
    return this.cache.getStats();
  }
}

module.exports = InstructionManager;
